"""exercise sets

Revision ID: 9a57bef80173
Revises: d55c7662240d
Create Date: 2025-08-15 20:41:48.294767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a57bef80173'
down_revision: Union[str, Sequence[str], None] = 'd55c7662240d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_sets',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('weight', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('(rpe BETWEEN 1 AND 10)', name='ck_exercise_set_rpe_range'),
    sa.CheckConstraint('reps >= 0', name='ck_exercise_set_reps_not_negative'),
    sa.CheckConstraint('rest_seconds >= 0', name='ck_exercise_set_rest_not_negative'),
    sa.CheckConstraint('weight >= 0', name='ck_exercise_set_weight_not_negative'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'position', name='uq_exercise_set_position')
    )
    op.drop_constraint(op.f('exercises_workout_id_fkey'), 'exercises', type_='foreignkey')
    op.create_foreign_key('fk_exercises_workouts', 'exercises', 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exercises', 'weight')
    op.drop_column('exercises', 'sets')
    op.drop_column('exercises', 'reps')
    op.add_column('workouts', sa.Column('name', sa.String(), nullable=False))
    op.add_column('workouts', sa.Column('workout_type', sa.String(), nullable=False))
    op.add_column('workouts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_workouts_users', 'workouts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.drop_column('workouts', 'user_id')
    op.drop_column('workouts', 'workout_type')
    op.drop_column('workouts', 'name')
    op.add_column('exercises', sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('exercises', sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('exercises', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.create_foreign_key(op.f('exercises_workout_id_fkey'), 'exercises', 'workouts', ['workout_id'], ['id'])
    op.drop_table('exercise_sets')
    # ### end Alembic commands ###
