"""merged user and profile

Revision ID: d22e24fda7e5
Revises: d9d1a3912079
Create Date: 2025-08-04 20:35:21.761984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd22e24fda7e5'
down_revision: Union[str, Sequence[str], None] = 'd9d1a3912079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("DELETE FROM users")
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=False))
    op.drop_constraint(op.f('users_profile_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'profile_id')
    op.drop_table('profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_profile_id_fkey'), 'users', 'profiles', ['profile_id'], ['id'])
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    op.drop_column('users', 'first_name')
    op.create_table('profiles',
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', name='genderenum'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey'))
    )
    # ### end Alembic commands ###
